// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: proto/logging/logging.proto

package logging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_DEBUG LogLevel = 0
	LogLevel_INFO  LogLevel = 1
	LogLevel_WARN  LogLevel = 2
	LogLevel_ERROR LogLevel = 3
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "DEBUG",
		1: "INFO",
		2: "WARN",
		3: "ERROR",
	}
	LogLevel_value = map[string]int32{
		"DEBUG": 0,
		"INFO":  1,
		"WARN":  2,
		"ERROR": 3,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_logging_logging_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_proto_logging_logging_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_logging_logging_proto_rawDescGZIP(), []int{0}
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=logging.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_logging_logging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logging_logging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_logging_logging_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_DEBUG
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type PushLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *LogEntry              `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushLogRequest) Reset() {
	*x = PushLogRequest{}
	mi := &file_proto_logging_logging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLogRequest) ProtoMessage() {}

func (x *PushLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logging_logging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLogRequest.ProtoReflect.Descriptor instead.
func (*PushLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_logging_logging_proto_rawDescGZIP(), []int{1}
}

func (x *PushLogRequest) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type PushLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushLogResponse) Reset() {
	*x = PushLogResponse{}
	mi := &file_proto_logging_logging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLogResponse) ProtoMessage() {}

func (x *PushLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logging_logging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLogResponse.ProtoReflect.Descriptor instead.
func (*PushLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_logging_logging_proto_rawDescGZIP(), []int{2}
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	MinLevel      LogLevel               `protobuf:"varint,2,opt,name=min_level,json=minLevel,proto3,enum=logging.LogLevel" json:"min_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_proto_logging_logging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logging_logging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_logging_logging_proto_rawDescGZIP(), []int{3}
}

func (x *StreamLogsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *StreamLogsRequest) GetMinLevel() LogLevel {
	if x != nil {
		return x.MinLevel
	}
	return LogLevel_DEBUG
}

type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	MinLevel      LogLevel               `protobuf:"varint,2,opt,name=min_level,json=minLevel,proto3,enum=logging.LogLevel" json:"min_level,omitempty"`
	Since         int64                  `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_proto_logging_logging_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logging_logging_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_logging_logging_proto_rawDescGZIP(), []int{4}
}

func (x *GetLogsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetLogsRequest) GetMinLevel() LogLevel {
	if x != nil {
		return x.MinLevel
	}
	return LogLevel_DEBUG
}

func (x *GetLogsRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

func (x *GetLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_proto_logging_logging_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logging_logging_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_logging_logging_proto_rawDescGZIP(), []int{5}
}

func (x *GetLogsResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_logging_logging_proto protoreflect.FileDescriptor

const file_proto_logging_logging_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/logging/logging.proto\x12\alogging\"\x85\x02\n" +
	"\bLogEntry\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12'\n" +
	"\x05level\x18\x02 \x01(\x0e2\x11.logging.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12A\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2!.logging.LogEntry.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x0ePushLogRequest\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.logging.LogEntryR\x05entry\"\x11\n" +
	"\x0fPushLogResponse\"[\n" +
	"\x11StreamLogsRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12.\n" +
	"\tmin_level\x18\x02 \x01(\x0e2\x11.logging.LogLevelR\bminLevel\"\x84\x01\n" +
	"\x0eGetLogsRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12.\n" +
	"\tmin_level\x18\x02 \x01(\x0e2\x11.logging.LogLevelR\bminLevel\x12\x14\n" +
	"\x05since\x18\x03 \x01(\x03R\x05since\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\">\n" +
	"\x0fGetLogsResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.logging.LogEntryR\aentries*4\n" +
	"\bLogLevel\x12\t\n" +
	"\x05DEBUG\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\b\n" +
	"\x04WARN\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x032\xc7\x01\n" +
	"\n" +
	"LogService\x12<\n" +
	"\aPushLog\x12\x17.logging.PushLogRequest\x1a\x18.logging.PushLogResponse\x12=\n" +
	"\n" +
	"StreamLogs\x12\x1a.logging.StreamLogsRequest\x1a\x11.logging.LogEntry0\x01\x12<\n" +
	"\aGetLogs\x12\x17.logging.GetLogsRequest\x1a\x18.logging.GetLogsResponseB0Z.github.com/eddisonso/log-service/proto/loggingb\x06proto3"

var (
	file_proto_logging_logging_proto_rawDescOnce sync.Once
	file_proto_logging_logging_proto_rawDescData []byte
)

func file_proto_logging_logging_proto_rawDescGZIP() []byte {
	file_proto_logging_logging_proto_rawDescOnce.Do(func() {
		file_proto_logging_logging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logging_logging_proto_rawDesc), len(file_proto_logging_logging_proto_rawDesc)))
	})
	return file_proto_logging_logging_proto_rawDescData
}

var file_proto_logging_logging_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_logging_logging_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_logging_logging_proto_goTypes = []any{
	(LogLevel)(0),             // 0: logging.LogLevel
	(*LogEntry)(nil),          // 1: logging.LogEntry
	(*PushLogRequest)(nil),    // 2: logging.PushLogRequest
	(*PushLogResponse)(nil),   // 3: logging.PushLogResponse
	(*StreamLogsRequest)(nil), // 4: logging.StreamLogsRequest
	(*GetLogsRequest)(nil),    // 5: logging.GetLogsRequest
	(*GetLogsResponse)(nil),   // 6: logging.GetLogsResponse
	nil,                       // 7: logging.LogEntry.AttributesEntry
}
var file_proto_logging_logging_proto_depIdxs = []int32{
	0, // 0: logging.LogEntry.level:type_name -> logging.LogLevel
	7, // 1: logging.LogEntry.attributes:type_name -> logging.LogEntry.AttributesEntry
	1, // 2: logging.PushLogRequest.entry:type_name -> logging.LogEntry
	0, // 3: logging.StreamLogsRequest.min_level:type_name -> logging.LogLevel
	0, // 4: logging.GetLogsRequest.min_level:type_name -> logging.LogLevel
	1, // 5: logging.GetLogsResponse.entries:type_name -> logging.LogEntry
	2, // 6: logging.LogService.PushLog:input_type -> logging.PushLogRequest
	4, // 7: logging.LogService.StreamLogs:input_type -> logging.StreamLogsRequest
	5, // 8: logging.LogService.GetLogs:input_type -> logging.GetLogsRequest
	3, // 9: logging.LogService.PushLog:output_type -> logging.PushLogResponse
	1, // 10: logging.LogService.StreamLogs:output_type -> logging.LogEntry
	6, // 11: logging.LogService.GetLogs:output_type -> logging.GetLogsResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_logging_logging_proto_init() }
func file_proto_logging_logging_proto_init() {
	if File_proto_logging_logging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logging_logging_proto_rawDesc), len(file_proto_logging_logging_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logging_logging_proto_goTypes,
		DependencyIndexes: file_proto_logging_logging_proto_depIdxs,
		EnumInfos:         file_proto_logging_logging_proto_enumTypes,
		MessageInfos:      file_proto_logging_logging_proto_msgTypes,
	}.Build()
	File_proto_logging_logging_proto = out.File
	file_proto_logging_logging_proto_goTypes = nil
	file_proto_logging_logging_proto_depIdxs = nil
}
